name: Verify Build Workflow
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [main]
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'CODE_OF_CONDUCT*'
    branches: [main]

jobs:
  build-verify:
    name: Verify Build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apicurio'
    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check Java Version
        run: java -version

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Project
        run: ./mvnw clean install